# Numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array(list(range(10)))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
type(a)  
# n dimensional array

numpy.ndarray

In [ ]:
# increament every element by 5
# doesnt update the original
a + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# saving the updated in a new one
b = a-5
print(b, type(b))

# can do any + - * / ** //

[-5 -4 -3 -2 -1  0  1  2  3  4] <class 'numpy.ndarray'>


In [ ]:
# attribute to get dimensions and size
b.shape

(10,)

In [ ]:
# changing shape
b = b.reshape((-1,1))
# first arg is a tuple defining shape, -1 is no change in prev value of 10, 
# 1 is 1 column

# next arg is order 
print(b)
b.shape

[[ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]]


(10, 1)

## Array operations

In [ ]:
b = a+5
c = a - 10


In [ ]:
# simply add corresponding elements
print(a, b)
a+b
# can do any of the arithmatic operations

[0 1 2 3 4 5 6 7 8 9] [ 5  6  7  8  9 10 11 12 13 14]


array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [ ]:
# wont do if len not same
t1 = np.array(list(range(4)))
t2 = np.array(list(range(3)))
# t1*t2
# ValueError: operands could not be broadcast together with shapes (4,) (3,) 

ValueError: ignored

In [ ]:
t1 = (a+5).reshape((-1,1))
print(a, t1)
a+t1

In [ ]:
d = np.array([[1,2,3],[4,5,6]])
print(d.shape)
d.reshape((3,2))
d.shape

(2, 3)


(2, 3)

## Functions of Numpy

In [ ]:
# matrix of all 0

# a = np.zeros((3,4))
a = np.zeros((3,4), dtype=int)    # can also use "int"
a
# by default dtype is float

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
e = np.zeros((3,3,3))
e

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# matrix of all values 1
a = np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [ ]:
# identity matrix 
i = np.identity(4, dtype=int)
i

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
f = np.ones((4,3), dtype=int)*5
f = np.zeros((4,3), dtype=int)+5
f

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

## Random functions

In [ ]:
np.random.randint(1,10, (5,1))
# randint(low, high=None, size=None, dtype=int)

array([[1],
       [1],
       [9],
       [3],
       [4]])

In [ ]:
a = np.random.randint(1,10, (3,5))
a

array([[8, 9, 5, 7, 5],
       [8, 7, 2, 9, 6],
       [2, 5, 3, 7, 1]])

In [ ]:
# slicing
print(a.shape)
print(a[ 1: , :3 ])  # rs:re, cs:ce row column start end

(3, 5)
[[8 7 2]
 [2 5 3]]


## More functions

min, max
mean, variance, sd

In [ ]:
a = np.array([[1,3],[4,2]])
a

array([[1, 3],
       [4, 2]])

In [ ]:

print (a.min())
print (a.max())
print (np.min(a))
print (np.max(a))

1
4
1
4


In [ ]:
print( np.std(a) )
print( np.std(a , axis = 0) )
# axis 0 is row wise, so std of every row individually
print( np.std(a , axis = 1) )
# column wise so basically the nth dimension

1.118033988749895
[1.5 0.5]
[1. 1.]


In [ ]:
print(np.var(a))
print(np.var(a, 0))
print(np.var(a, 1))

1.25
[2.25 0.25]
[1. 1.]


In [ ]:
# same value because of seed
for i in range (10):
  np.random.seed(7)
  print(np.random.randint(10))

4
4
4
4
4
4
4
4
4
4


In [ ]:
#STACK

a = np.array ([1,2,3])
b = np.array([3,4,'a'])
np.stack((a,b))

# shape should be same data type as seen can be different
# simply stacks up the args in tuple making a matrix

array([['1', '2', '3'],
       ['3', '4', 'a']], dtype='<U21')

Products

In [ ]:
a = np.array ([1,2])
b = np.array([3,4])


# dot product
print(np.dot(a,b))

# vector/cartesian/cross 
print(np.cross(a,b))

11
-2


In [ ]:
# Hackerrank question : Dot and Cross

import numpy as np
n = int(input())
a = []
for i in range(n):
  a.append(list(map(int, input().split())))
b = []
for i in range(n):
  b.append(list(map(int, input().split())))

#a = np.array(a)
#b = np.array(b)

print(np.dot(a,b))


2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [ ]:
# Hackerrank question : Mean, Var and Std

import numpy as np

n , m = list(map(int, input().split()))
#l = [int(i) for i in input().strip().split()]
arr = []
for i in range (n):
  arr.append(list(map(int, input().split())))

np.set_printoptions(legacy="1.13") 
# without this the format precision was a litt;e different
print(np.mean(arr, axis = 1))
print(np.var(arr, axis=0))
print(np.std(arr))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [ ]:
# Hackerrank question : Transpose and Flatten

# TRANSPOSE : aji for aij
# FLATTEN : [1,2],[3,4] = [1,2,3,4]

import numpy as np
n , m = list(map(int, input().split()))
arr = []
for i in range (n):
  arr.append([int(i) for i in input().strip().split()])

arr = np.array(arr)
print(np.transpose(arr))
print(arr.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]
